import * as cdk from 'aws-cdk-lib';
import * as wafv2 from 'aws-cdk-lib/aws-wafv2';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface SecurityStackProps extends cdk.StackProps {
  /** ARN of the ALB to associate the WAF WebACL with. */
  albArn: string;
  /** Logical environment name used for resource naming and CFN exports. */
  envName?: string;
}

/**
 * SecurityStack provisions the WAF and secrets management layer:
 * - WAF WebACL with IP-based rate limiting (1000 req/5 min) and AWS managed rules
 * - WAF WebACL association with the ALB
 * - Secrets Manager entries for Clerk API keys and Redis auth token
 *
 * DB credentials are auto-generated and stored by DatabaseStack. This stack
 * creates the remaining application secrets as placeholders; operators populate
 * real values after deployment.
 */
export class SecurityStack extends cdk.Stack {
  public readonly wafWebAcl: wafv2.CfnWebACL;
  public readonly clerkPublishableKeySecret: secretsmanager.Secret;
  public readonly clerkSecretKeySecret: secretsmanager.Secret;
  public readonly redisAuthTokenSecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props: SecurityStackProps) {
    super(scope, id, props);

    const envName = props.envName ?? 'dev';

    // ── WAF WebACL ─────────────────────────────────────────────────────────
    this.wafWebAcl = new wafv2.CfnWebACL(this, 'AppWebAcl', {
      name: `${envName}-ashta-chamma-waf`,
      // REGIONAL scope for ALB association (as opposed to CLOUDFRONT for CF distributions).
      scope: 'REGIONAL',
      defaultAction: { allow: {} },
      visibilityConfig: {
        sampledRequestsEnabled: true,
        cloudWatchMetricsEnabled: true,
        metricName: `${envName}-ashta-chamma-waf`,
      },
      rules: [
        {
          // Rate-limit rule: block IPs that exceed 1000 requests in 5 minutes.
          name: 'RateLimitRule',
          priority: 1,
          action: { block: {} },
          visibilityConfig: {
            sampledRequestsEnabled: true,
            cloudWatchMetricsEnabled: true,
            metricName: `${envName}-rate-limit`,
          },
          statement: {
            rateBasedStatement: {
              // Maximum requests per IP in any 5-minute window.
              limit: 1000,
              aggregateKeyType: 'IP',
            },
          },
        },
        {
          // AWS managed rule set: protects against common web exploits (OWASP top 10).
          name: 'AWSManagedRulesCommonRuleSet',
          priority: 2,
          overrideAction: { none: {} },
          visibilityConfig: {
            sampledRequestsEnabled: true,
            cloudWatchMetricsEnabled: true,
            metricName: `${envName}-aws-common-rules`,
          },
          statement: {
            managedRuleGroupStatement: {
              name: 'AWSManagedRulesCommonRuleSet',
              vendorName: 'AWS',
            },
          },
        },
        {
          // Known bad inputs: blocks requests matching known attack patterns.
          name: 'AWSManagedRulesKnownBadInputsRuleSet',
          priority: 3,
          overrideAction: { none: {} },
          visibilityConfig: {
            sampledRequestsEnabled: true,
            cloudWatchMetricsEnabled: true,
            metricName: `${envName}-bad-inputs-rules`,
          },
          statement: {
            managedRuleGroupStatement: {
              name: 'AWSManagedRulesKnownBadInputsRuleSet',
              vendorName: 'AWS',
            },
          },
        },
      ],
    });

    // Associate the WAF WebACL with the ALB so all inbound traffic is inspected.
    new wafv2.CfnWebACLAssociation(this, 'WafAlbAssociation', {
      resourceArn: props.albArn,
      webAclArn: this.wafWebAcl.attrArn,
    });

    // ── Secrets Manager entries ────────────────────────────────────────────
    // Clerk publishable key: safe to embed in client bundle but stored here for
    // consistency and to support server-side rendering use cases.
    this.clerkPublishableKeySecret = new secretsmanager.Secret(
      this,
      'ClerkPublishableKeySecret',
      {
        secretName: `${envName}/ashtachamma/clerk-publishable-key`,
        description:
          'Clerk publishable API key — populate after creating the Clerk application',
        generateSecretString: {
          secretStringTemplate: JSON.stringify({ key: 'REPLACE_ME' }),
          generateStringKey: '_autogenerated_placeholder',
        },
      },
    );

    // Clerk secret key: server-side only; used for backend Clerk SDK calls.
    this.clerkSecretKeySecret = new secretsmanager.Secret(
      this,
      'ClerkSecretKeySecret',
      {
        secretName: `${envName}/ashtachamma/clerk-secret-key`,
        description:
          'Clerk secret API key — populate after creating the Clerk application',
        generateSecretString: {
          secretStringTemplate: JSON.stringify({ key: 'REPLACE_ME' }),
          generateStringKey: '_autogenerated_placeholder',
        },
      },
    );

    // Redis auth token: random 32-character token for future Redis AUTH enablement.
    // Store the token here; configure ElastiCache authToken when upgrading to production.
    this.redisAuthTokenSecret = new secretsmanager.Secret(
      this,
      'RedisAuthTokenSecret',
      {
        secretName: `${envName}/ashtachamma/redis-auth-token`,
        description: 'Redis AUTH token for ElastiCache in-transit authentication',
        generateSecretString: {
          passwordLength: 32,
          // Exclude characters that could break Redis AUTH or URL encoding.
          excludeCharacters: '"@/\\',
          excludePunctuation: false,
        },
      },
    );

    // ── CloudFormation outputs ──────────────────────────────────────────────
    new cdk.CfnOutput(this, 'WafWebAclArn', {
      value: this.wafWebAcl.attrArn,
      description: 'WAF WebACL ARN',
      exportName: `${envName}-WafWebAclArn`,
    });
    new cdk.CfnOutput(this, 'ClerkPublishableKeySecretArn', {
      value: this.clerkPublishableKeySecret.secretArn,
      description: 'Secrets Manager ARN for Clerk publishable key',
      exportName: `${envName}-ClerkPublishableKeySecretArn`,
    });
    new cdk.CfnOutput(this, 'ClerkSecretKeySecretArn', {
      value: this.clerkSecretKeySecret.secretArn,
      description: 'Secrets Manager ARN for Clerk secret key',
      exportName: `${envName}-ClerkSecretKeySecretArn`,
    });
    new cdk.CfnOutput(this, 'RedisAuthTokenSecretArn', {
      value: this.redisAuthTokenSecret.secretArn,
      description: 'Secrets Manager ARN for Redis AUTH token',
      exportName: `${envName}-RedisAuthTokenSecretArn`,
    });
  }
}
